# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://cdn.cocoapods.org/'

target 'Shop' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  platform :ios, ’13.0’

  # Pods for Shop
  pod 'Alamofire', '~> 5.0'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'RealmSwift'
end
