# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'homework' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Quick'
  pod 'Nimble'
  pod 'OHHTTPStubs/Swift'
  pod 'RealmSwift'
  pod 'Magics'
  pod 'Alamofire'

  # Pods for homework

  target 'homeworkTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Quick'
    pod 'Nimble'
    pod 'OHHTTPStubs/Swift'
    pod 'RealmSwift'
    pod 'Magics'
    pod 'Alamofire'
  end

  target 'homeworkUITests' do
    # Pods for testing
  end

end
