# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'homework14' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  platform :ios, ’13.0’

  # Pods for homework14
  pod 'Alamofire', '~> 5.0'
  pod 'SVProgressHUD', :git => 'https://github.com/SVProgressHUD/SVProgressHUD.git'
  pod 'RealmSwift'

end
