# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
  # Comment the next line if you don't want to use dynamic frameworks

  # Pods for homework12

platform :ios, '13.0'
use_frameworks!

target 'homework12' do
  pod 'Alamofire', '~> 5.0'
  pod 'SVProgressHUD'
end
